---
name: push
on: 
  push: 
    branches:
        - '*'
jobs:
  build:
    needs: 
      - build
    uses: poornaakallam/workflows/.github/workflows/poc.yml@main
    with: 
      GITHUB_USER_TOKEN: ${{ needs.build.outputs.GITHUB_USER_TOKEN }}
      path: ~/.m2/repository
      key: "$RUNNER_OS-maven-$HASH_VALUE('**/pom.xml')"
      java-version: '17'
      cmd: mvn -f pom.xml versions:set -DnewVersion=SNAPSHOT
      build: mvn -f pom.xml clean package
      artifact: cd /home/runner/work/clone-repo-2/clone-repo-2/target
      zip: zip fr.zip
      #working-directory: ./
      upload-path: ${{github.workspace }}/target/fr.zip
    secrets:
      access-key: ${{ secrets.access_key }}
      secret-key: ${{secrets.secret_key}}

      

      
